PREFIX etl: <http://cambridgesemantics.com/ontologies/ETL#>
PREFIX sdi: <http://cambridgesemantics.com/ontologies/2015/08/SDIService#> 

SELECT
?etl_uri
?project_uri
?project_name
?job_uri
?job_name
?start_time
?end_time
?status
?job_run
WHERE
{
?project_uri a etl:DatasetProject ;
   etl:datasetName ?project_name ;
   etl:engineConfig ?etl_uri .
   OPTIONAL {
       ?project_uri etl:group/etl:item ?job_uri .
       ?job_uri etl:completeJobNames ?job_name .
       ?job_uri a etl:Job ;
           etl:completeJobNames ?job_name ;
           etl:jobRun ?job_run .
       ?job_run a ?jrt ;
    }
    OPTIONAL {
       ?job_run sdi:jobStartTime ?start_time ;
    }
    OPTIONAL {
       ?job_run sdi:jobEndTime ?end_time ;
           sdi:status ?status .
    }
}
ORDER BY ?project_uri ?job_uri


